version: '3.8'

services:
  mailgraper:
    build: .
    image: mailgraper:latest
    ports:
      - 8777:8777
    volumes:
      - ./src:/app
    networks:
      - yarascanlistener_default

networks:
  yarascanlistener_default:
    external: true
